- setup.py
- src/biopython/__init__.py
- tests/test_init.py
This allows to check which version of biopython is installed as suggested by PEP8:
```python
> import biopython
> biopython.__version__
"2.0a2"
```
> Make package version available (PEP8)

- doc/examples/scripts/sequence/ws_genome_search.py
- doc/examples/scripts/structure/adjacency_matrix.py
- doc/tutorial/sequence.rst
- doc/tutorial/structure.rst
- src/biotite/__init__.py
- src/biotite/sequence/__init__.py
- src/biotite/sequence/graphics/alignment.py
- src/biotite/structure/__init__.py
- src/biotite/structure/adjacency.pyx
- src/biotite/structure/sasa.pyx
- tests/structure/test_adjacency.py
- `AdjacencyMap` is now called `CellList`
- Use of `__cinit__()` instead of `__init__()`
- Fixed `AttributeError` in` __dealloc__()` when constructor call fails
> Renaming and improvement of AdjacencyMap

- src/biotite/sequence/align/alignment.py
Prior to this PR, the iteration over alignment objects yielded no elements. This PR forbids such an iteration.
> Alignment objects are not iterable

- doc/examples/scripts/structure/ku_superimposition.py
- src/biotite/structure/superimpose.py
- tests/structure/test_superimpose.py
Structure superimposition uses now boolean masks for selecting considered atoms. This increases the flexibility of the function.
> Superimposition uses boolean mask

- src/biotite/application/clustalo/app.py
- src/biotite/application/dssp/app.py
- src/biotite/application/mafft/app.py
- src/biotite/application/msaapp.py
- src/biotite/application/muscle/app.py
- src/biotite/temp.py
- tests/database/test_entrez.py
- tests/structure/test_gro.py
- tests/structure/test_pdb.py
The `temp` module uses `tempfile.mktemp()` to generate file names for temporary files in `.biotitetemp`.
> Temporary files with generated unique name

- src/biotite/structure/io/general.py
- src/biotite/structure/io/general.pyi
- tests/structure/test_generalio.py
Right now, loading a trajectory is a two-step because the template has to be loaded in memory before calling ```load_structure```. This can be reduced to a oneliner by allowing to submit strings as templates:
```python
from biotite.structure.io import load_structure
stack = load_structure("abc.xtc", template="abc.pdb")
```
> allow string/file-like as template for load_structure

- src/biotite/structure/io/mmtf/convertarray.pyx
- src/biotite/structure/io/mmtf/convertfile.pyx
- src/biotite/structure/io/pdbx/convert.py
- src/biotite/structure/io/pdbx/file.py
- tests/structure/test_pdb.py
- tests/structure/test_pdbx.py
This PR changes the mmCIF field that is read for the `AromArray` `res_id` field from `label_seq_id` to `auth_seq_id`. This brings two improvements:
- More consistency with PDB files
- For MMTF files, the `groupIdList` files can be used
- Additional distinction between multiple equal `HETERO` molecules
> Structures read from mmCIF files use 'auth_seq_id' instead of 'label_seq_id' for residue ID

- src/biotite/structure/io/pdb/file.py
- tests/structure/test_pdb.py
AtomArrays with more then 100k atoms cause an overflow of the atom_id field when written to a pdb file. This results in the the pdb_id field of pdb files to be larger then expected and results in broken files (cannot be parsed by biotite or other common programs). This patch fixes this behaviour by starting with atom_id = 1 once 99,999 is reached. A user warning is thrown if such a file is written.
> pdbs 'atom_id' field overflows when there are more than 100000 atoms

- src/biotite/structure/geometry.py
The doc for the "box" parameter in geometry.distance happend to end in the Returns section instead of Parameters leading to wrong autocomplete suggestions.
> Fix geometry.distance documentation

- src/biotite/structure/celllist.pyx
This PR introduces this type check, since the accidental exchange of an `AtomArray` with an `AtomArrayStack` can be quite common.
> TypeError is raises when 'AtomArrayStack' is given to 'CellList' instead of 'AtomArray'

- src/biotite/sequence/alphabet.py
This PR makes changes to the `LetterAlphabet` class, so that it internally uses `bytes` as symbols instead of `str`. This allows the class to encode sequences based on `bytes` instead of `str`, increasing the performance.
> LetterAlphabet internally uses bytes as symbols

- src/biotite/structure/filter.py
For more compatibility with Gromacs the function `filter_solvent()` does not check for the `hetero` annotation of atom arrays (or stacks).
> Solvent filter does not use 'hetero' field

- src/biotite/structure/io/gro/file.py
Without a newline GRO files cannot be opened in PyMOL
> GRO files are terminated with a newline 

- src/biotite/structure/io/pdb/file.py
- tests/structure/test_pdb.py
Furthermore, an issue in the PDB writer when having at least 200,000 atoms was fixed.
> PDB writer checks for residue ID overflow

- src/biotite/structure/io/gro/file.py
- tests/structure/test_gro.py
There is a small issue with the .gro input reader resulting in an exception if an empty box (x=y=z=0.000) is read in. This fixes this problem and also implements an appropriate unit test.
> handle dummy boxes in .gro correctly

- doc/apidoc.json
- src/biotite/structure/__init__.py
- src/biotite/structure/chains.py
- src/biotite/structure/geometry.py
- src/biotite/structure/residues.py
- tests/structure/test_chains.py
- tests/structure/test_geometry.py
This PR changes the `dihedral_backbone()` function:
- Added chain-level functionality, similar to the existing residue-level functionality
- The `chain_id`, parameter is removed, the function iterates over all chains
- Improved validity check for input atom arrays
> Revamped 'dihedral_bockbone()' function

- src/biotite/structure/geometry.py
- tests/structure/test_geometry.py
The result for multiple chains is concatenated along the wrong axis. For X frames, Y residues and Z chains, the result should be of the shape (X, Y*Z), but the current outbut is (X*Z, Y). This resolves this issue.
> dihedrals: correct output shape for multiple chains

- src/biotite/sequence/align/matrix.py
- src/biotite/sequence/align/multiple.pyx
- src/biotite/sequence/align/pairwise.pyx
As `SubstitutionMatrix` objects are immutable, this PR sets the internal score matrix read-only. The alignment function implemented in Cython are updated to accept also a read-only buffer for the score matrix.
> Read only score matrix in substitution matrices

- src/biotite/structure/io/general.py
- tests/structure/test_generalio.py
Keyword arguments submitted as **kwargs will be passed to the files `get_structure` method for non-trajectories (pdb, gro..) and to `read` for trajectories (xtc, tng, ....). It seems like no file format has additional arguments for both so far.
The only weak spot is template loading from a string, which won't get additional arguments. This would require creating (and maintaining) a list of allowed arguments for `read` and `get_structure` for every possible trajectory/template combination. Users can pass AtomArrays instead if it is required to pass additional arguments to a template.
> Allow passing additional keyword arguments to io.load_structure method

- src/biotite/structure/graphics/atoms.py
- src/biotite/structure/info/atoms.py
- src/biotite/structure/info/bonds.py
Msgpack 1.0 introduced a breaking change: The default value for `strict_map_key` was set from `False` to `True`. This PR fixes the implications.
> Fix for Msgpack 1.0

- src/biotite/structure/celllist.pyx
- tests/structure/test_celllist.py
When using a `CellList` with `periodic=True` and a `selection` out of bounds memory access is possible.
Furthermore, `create_adjacency_matrix()` did not return a symmetric matrix, when a `selection` was given
This PR fixes these issues.
> Fixing CellList when using 'periodic' in combination with 'selection'

- src/biotite/structure/io/dcd/file.py
- src/biotite/structure/io/netcdf/file.py
- src/biotite/structure/io/pdbx/convert.py
- src/biotite/structure/io/tng/file.py
- src/biotite/structure/io/trajfile.py
- src/biotite/structure/io/trr/file.py
- src/biotite/structure/io/xtc/file.py
- tests/structure/test_pdbx.py
- tests/structure/test_trajectory.py
The new functions `read_iter()` and `read_iter_structure()` allow frame-wise iteration over trajectory files.
This is especially useful for trajectory files, that are too large to fit into memory.
> Adding 'read_iter()' and 'read_iter_structure()' class methods to trajectory files

- src/biotite/structure/hbond.py
- src/biotite/structure/io/pdbx/convert.py
Most structures in the PDB have no annotated hydrogen atoms. If such a structure without hydrogens is given to `hbond()` no hydrogen bonds will be found.
Since this mistake might happen quite often, this PR adds a note to the function's docstring that a structure with annotated hydrogen atoms is required.
> Adding note that 'hbond' requires hydrogen atoms

- src/biotite/file.py
- src/biotite/structure/io/mmtf/file.py
- src/biotite/structure/io/npz/file.py
A common mistake when reading file-like objects with `biotite.File.read()` is that the file object might be opened in the correct mode (text/binary). An example is issue #193. The current errors raised in this case are not easily understandable, as it occurs somewhere within the the file parsing procedure, when a `str` is expected but `bytes` is given (or vice versa). In order to catch the mistake before it, this PR adds a file mode check in `read()` and `write()` in `TextFile`, `MMTFFile` and `NpzFile`.
> Checking file mode when reading/writing files

- doc/apidoc.json
- src/biotite/structure/chains.py
- src/biotite/structure/filter.py
- src/biotite/structure/io/mmtf/convertfile.pyx
- src/biotite/structure/io/pdb/convert.py
- src/biotite/structure/io/pdb/file.py
- src/biotite/structure/io/pdbx/convert.py
- src/biotite/structure/residues.py
- tests/structure/test_filter.py
- tests/structure/test_gro.py
This PR closes #194, by introducing a new *altloc* ID handling when reading structures:
Instead of selecting the *altloc* IDs for each residue individually, three options would be available for the `'altloc'` parameter:
- `'first'` - Use atoms that have the first *altloc* ID appearing in a residue.
- `'occupancy'` - Use atoms that have the *altloc* ID with the highest occupancy for a residue.
- `'all'` - Use all atoms. When this option is chosen, the `altloc_id` annotation array is added to the returned structure to enable the user to filter the required *altloc* IDs in a custom way.
This PR adds the `filter_first_altloc()` and `filter_highest_occupancy_altloc()` functions for the `'first'` and `'occupancy'` option, respectively.
The old `filter_altloc()` function is removed.
These new …
> Refectored altloc ID handling

- doc/extensions.rst
Although the Biotite-PyMOL-interface *Ammolite* is still in Pre-Alpha, this PR adds a link to *Ammolite's* documentation to the *Extensions* page.
> Adding 'Ammolite' as extension package

- src/biotite/sequence/io/fasta/convert.py
- src/biotite/sequence/io/fastq/convert.py
- tests/sequence/data/nuc.fasta
- tests/sequence/test_fasta.py
This PR fixes the the wrong handling of ambiguous nucleotide symbols in the high-level access functions of FASTA/FASTQ, as mentioned in #232.
> Correct handling of ambiguous symbols when reading from FASTA/FASTQ

- src/biotite/file.py
- src/biotite/sequence/io/fasta/file.py
- src/biotite/sequence/io/fastq/file.py
- tests/sequence/test_fasta.py
- tests/sequence/test_fastq.py
Currently, the only way to read FASTA/FASTQ files requires parsing the entire files and storing the lines in a `TextFile` object.
However, these files might contain a large number of entries, so this may become a major memory issue. This PR adds the `read_iter()` static method to both files classes, allowing element-wise iteration without storing the entire file.
> Add iterable parsing of FASTA/FASTQ files

- doc/examples/scripts/structure/watson_crick.py
- src/biotite/structure/graphics/atoms.py
In the current version of *Matplotlib* the axis lenghts of the 3D plot box are not guaranteed to be equal. In fact, the z-axis is usually shorter than the x- and y-axis. This leads to distortions of the plotted structure in the z-direction in `plot_atoms()`. To overcome this problem this PR sets the box aspect ratio to the same value in all three dimensions in `plot_atoms()`.
> Fix 3D plot axis lengths in `plot_atoms()`

- src/biotite/application/msaapp.py
- src/biotite/structure/info/__init__.py
- src/biotite/structure/info/standardize.py
- tests/structure/test_info.py
Some functionality in *Biotite* or self written function require atoms in a residue to be in a standardized order. For example, the superimposition of two structures require that the atoms in both structures are in the same order. This PR adds the `standardize_order()` function, which returns indices to an input `AtomArray` or `AtomArrayStack` that, if applied, residue-wise reorders the atoms in the structure, so that it has the standard order as used in the *RCSB PDB*.
This PR could be used to fix #237.
> Add 'standardize_order()'

- src/biotite/sequence/io/fasta/convert.py
- src/biotite/sequence/io/genbank/sequence.py
- src/biotite/sequence/seqtypes.py
- tests/sequence/data/prot.fasta
- tests/sequence/test_fasta.py
This PR adds weak support for selenocysteine (`U`) symbols in FASTA and GenBank files:
When an `U` appears in a protein sequence, it is automatically converted into cysteine (`C`) and a warning is raised.
To allow simple handling of unaltered sequences in GenBank files, the function `genbank.get_raw_sequence()` is added, returning the sequence as string. This is not necessary in the `fasta` subpackage, because the low-level API in `FastaFile`already provides this functionality.
Due to these changes, the automatic sequence type detection in `fasta.get_sequence()` and `fasta.get_sequences()` would almost always detect an ambiguous RNA sequene as protein sequence. Hence, now the conversion into a `NucleotideSequence` is tested at first and then the conversion into a `ProteinSequence` is …
> Selenocysteine support for FASTA and GenBank files

- doc/tutorial/src/database.py
- doc/tutorial/src/sequence.py
- doc/tutorial/src/structure.py
- src/biotite/application/clustalo/app.py
- src/biotite/application/dssp/app.py
- src/biotite/application/localapp.py
- src/biotite/application/msaapp.py
- src/biotite/application/muscle/app.py
- src/biotite/application/sra/app.py
This PR addresses #243. It sets `delete` to `False` in the constructor of `NamedTemporaryFile` and manually deletes the temporay file in `Application.cleanup()`. This workaround was necessary as Windows does not allow to reopen temporary files a second time, if `delete` is `True`. However, reopening temporary files is required in the executed CLI programs.
> Fixes #243

- src/biotite/structure/bonds.pyx
- tests/structure/test_bonds.py
In the constructor of `BondList` the provided `bonds` parameter is checked for out-of-bounds values regarding the `atom_count`.
Previously however, not only the bond indices but also the `BondType` were checked, which does not make sense, since the `BondType` values are not restrained by `atom_bount`, but by the values in the `BondType` enum.
This subtle error has only effect in the rare occurence of an `AtomArray` with its length equal or smaller than one of its bond orders
*Cyanide* (`CN`) is such are rare case (#252): It contains 3 atoms but also a triple bond.
This PR fixes the bound check. Hence this PR also fixes #252.
> Fix bounds check for BondType

- doc/apidoc.json
- src/biotite/structure/basepairs.py
- tests/structure/test_basepairs.py
This PR improves the pre-selection of potential stacking partners in  `base_stacking()`. 
`_get_proximate_basepair_candidates()` was renamed to `_get_proximate_residues()`. Also the function is now more generalized:
- The selection of atoms whose distances should be compared is now specified by a boolean mask
- The default cutoff value was removed
Previously `base_stacking()` pre-selected potential stacking candidates using `_get_proximate_basepair_candidates()`, with a cutoff distance between N/O atoms pairs of 15Å. The function was originally implemented for pre-selecting potential basepair candidates for `base_pairs()` based on the plausibility of hydrogen bonds. In this case the function was used to approximate the distance between the bases. 
However, in order to approximate the …
> Improve 'base_stacking()'

- src/biotite/structure/io/pdb/file.py
Prior to this PR `PDBFile` writes the B factor with 3 decimal places, although the specification states 2 decimal places. This PR fixes that.
> Fix number of decimal places of B-factor in PDB files

- doc/apidoc.json
- src/biotite/structure/__init__.py
- src/biotite/structure/atoms.py
- src/biotite/structure/bonds.pyx
- src/biotite/structure/chains.py
- src/biotite/structure/molecules.py
- src/biotite/structure/residues.py
- tests/structure/test_molecules.py
This PR adds functions to work with atoms on molecule-level, i.e. groups of atoms that are connected via bonds in a `BondList`:
- `get_molecule_indices()`
- `get_molecule_masks()`
- `molecule_iter()`
Furthermore, the performance of `structure.find_connected()` is increased.
> Add molecule-level functionalities

- src/biotite/structure/bonds.pyx
- tests/structure/test_bonds.py
After indexing a `BondList` with an undordered index array, the new `BondList` may contain bonds, where the atom indices are not sorted anymore. However, many methods of `BondList` rely on the assumption, that the indices in each bond are sorted. Therefore, these methods may return wrong results with such an invalid `BondList`.
This PR fixes this issue, by sorting all bonds after indexing with an index array.
> Fix unordered bond pairs after indexing BondList with unordered array

- src/biotite/structure/basepairs.py
- tests/structure/test_basepairs.py
This PR fixes the following bugs and adds a test function checking their presence:
- The `min_atoms_per_base` argument was only considered for non-canonical bases. This led to an exception being thrown if no atoms in a base with a canonical residue name matched the corresponding reference base.
- If no base pairs were found, an exception was thrown.
> Fix bugs in `base_pairs()`

- src/biotite/structure/pseudoknots.py
This PR improves the performance of `pseudoknots()`.
The helper function `_conflict_cliques()`  was adjusted to allow the separation and thus independent computation of nested cliques of conflicting regions. Previously, the function was only able to separate neighboring cliques of conflicting regions.
> Improve performance of pseudoknot detection

- doc/examples/scripts/sequence/gpcr_evolution.py
- doc/examples/scripts/structure/rotamer_library.py
- setup.py
- src/biotite/sequence/phylo/tree.pyx
- src/biotite/structure/bonds.pyx
- src/biotite/structure/io/mmtf/convertfile.pyx
- tests/sequence/test_phylo.py
- tests/structure/test_bonds.py
- tests/test_doctest.py
This PR add the `networkx` package as dependency to *Biotite* and uses it at several places in the source code:
- The new function `structure.find_rotatable_bonds`
- The method `structure.BondList.as_graph()`
- The method `structure.Tree.as_graph()`
*NetworkX* is an well supported, easily installable package that is already used in some examples in the gallery. Therefore, I think it is reasonable to add this package as additional dependency.
> Add 'NetworkX' package as dependency

- doc/static/biotite.css
- src/biotite/sequence/seqtypes.py
This PR adds a separator line and a small margin between the list of methods in the API reference section of the documentation. Furthermore it adds docstrings for two functions which have not got one, yet.
> Add separation between methods in the API reference

- src/biotite/structure/bonds.pyx
- src/biotite/structure/charges.pyx
- src/biotite/structure/io/pdbqt/convert.py
- src/biotite/structure/io/pdbqt/file.py
- tests/structure/test_bonds.py
The current bond types are not able to distinguish between formal single or double bonds for aromatic bonds. This circumstance gives rise to some issues were this information would be relevant, e.g. for drawing structural formulas or determining if an aromatic nitrogen atom has a hydrogen or not.
This PR changes the `BondType` enum by splitting `BondType.AROMATIC` into `BondType.AROMATIC_SINGLE` and `BondType.AROMATIC_DOUBLE` which convey both informations: Whether a bond is part of an aromatic system and whether it is formally a single or double bond.
> Include formal bond order in aromatic bond type

- setup.py
- src/biotite/structure/io/pdb/file.py
- tests/structure/test_pdb.py
This PR fixes two issues in 'structure.PDBFIle':
- 'get_model_count()' returns 0 if the file contains no `MODEL` line
- Formal charges are written in the format e.g. `+1` instead of the correct format `1+`
> Fixes for 'PDBFile'

- src/biotite/structure/celllist.pyx
In the current implementation `CellList.get_atoms()` and `CellList.get_adjacency_matrix()` check two adjacent cells if the `radius` is exactly the `cell_size`. However, checking the direct adjacent cell is sufficient in this case. This PR fixes that. The results are the same, but the performance increases in this common case.
> Fix too large cell radius

- src/biotite/structure/atoms.py
- tests/structure/test_info.py
Previously setting an annotation in an `AtomArray` via `set_annotation()` or `__setitem__()` uses the *dtype* of the given array, even if an array already exists for this category. This can lead to undesired dtypes when e.g. reading a structure from a file.
This PR changes this behavior: If an annotation array already exists for the annotation category, its dtype will also be used for the new array given by `set_annotation()` or `__setitem__()`.
> Setting an exisiting annotation does not change dtype

- src/biotite/structure/bonds.pyx
- src/biotite/structure/io/mmtf/convertfile.pyx
- src/biotite/structure/io/pdb/convert.py
- src/biotite/structure/io/pdb/file.py
- tests/structure/test_pdb.py
This PR allows reading bonds from `CONECT` records in `PDBFile.get_structure()` if `include_bonds` is set to `True`. `PDBFile.set_structure()` automatically writes `CONECT` records if the `Atomarray` has an associated `BondList`.
Furthermore, `connect_via_distance()` and `connect_via_residue_names()` get the optional `atom_mask` and `inter_residue` parameters for more control over the created bonds.
Closes #329 .
> Read and write bonds from/to PDB files

- src/biotite/structure/io/pdb/convert.py
- src/biotite/structure/io/pdb/file.py
- tests/structure/test_pdb.py
This PR adds a test and clarifies the docstring regarding the bond parsing from PDB files.
> Catch error if 'CRYST1' record is corrupt in PDBfile

- .github/workflows/test.yml
- doc/apidoc.json
- doc/conf.py
- doc/viewcode.py
- src/biotite/sequence/align/kmeralphabet.pyx
- src/biotite/sequence/align/kmersimilarity.pyx
- src/biotite/sequence/align/kmertable.pyx
- src/biotite/sequence/graphics/plasmid.py
- src/biotite/sequence/io/fastq/convert.py
- src/biotite/sequence/io/general.py
- src/biotite/structure/charges.pyx
- tests/test_modname.py
Up to now the source code for a class or function in the API reference points to a page in the *Biotite* documentation using *Sphinx* `viewcode`. This PR changes this, so that the code points to the corresponding GitHub page with highlighted lines using `linkcode`.
> Documentation: API reference point to the source code on GitHub

- src/biotite/file.py
- src/biotite/sequence/io/fasta/file.py
- src/biotite/sequence/io/fastq/file.py
- src/biotite/structure/io/netcdf/file.py
- src/biotite/structure/io/trajfile.py
- tests/sequence/test_fasta.py
- tests/sequence/test_fastq.py
- tests/structure/test_trajectory.py
This PR adds the static `writer_iter()` method to the `TextFile`, `FastaFile`, `FastqFile` and `TrajectoryFile` classes. Analogous to `read_iter()` it allows to write a file entry by entry, without the need to hold the entire file content in memory. The definition of *entry* is dependent on the type of file.
> Add 'writer_iter()' static method

- .github/workflows/test.yml
- environment.yml
- src/biotite/application/application.py
- src/biotite/application/muscle/__init__.py
- src/biotite/application/muscle/app3.py
- src/biotite/application/muscle/app5.py
- tests/application/test_msa.py
- tests/sequence/align/test_multiple.py
- tests/sequence/align/test_pairwise.py
- tests/test_doctest.py
This PR adds support for *Muscle* version 5. Since *Muscle* 5 is a major rewrite of Muscle 3 with other CLI options, the interface is separated into two `Application` classes: `MuscleApp` for the original *Muscle* 3 and `Muscle5App` for the new *Muscle* 5.
> Add support for Muscle 5

- src/biotite/structure/transform.py
- tests/structure/test_transform.py
If origin_direction or target_direction are shape (1, 3), it is
possible to raise a DeprecationWaring when declaring v_c.
I addressed this by adding a check of the shape of these inputs.
End users could call np.squeeze to ensure the vectors have the
correct shape.
If origin_direction or target_direction have some other shape, the
rest of the code won't work anyway.
> Ensure align_vectors inputs are correct

- src/biotite/file.py
- src/biotite/structure/io/pdb/file.py
Removed duplicated code for writing AtomArray vs AtomArrayStack data,
fixed a minor bug affecting atom name alignment.
> Minor clean up of PDBFile.set_structure

- CONTRIB.rst
- src/biotite/structure/bonds.pyx
- src/biotite/structure/io/ctab.py
- src/biotite/structure/io/pdbx/convert.py
- src/biotite/structure/io/pdbx/file.py
- tests/structure/test_pdbx.py
Hi
We are actually using in our project a patched version of biotite `v0.29.0`. Can those minor patches be included in the main codebase if it suits the contributing guidelines ?
* `biotite.structure.bonds.connect_via_distances`
* Allow the user to change the default `BondType` in the generated `BondList`.
* `biotite.structure.io.ctab.write_structure_to_ctab`
* Format file using black formatter (`black -l 79 ...`) 
* Add `default_bond_type` as a keyword parameter
* `biotite.structure.io.pdbx.file.PDBxFile.set_category`
* Format file using black formatter
* Ensure `_quote` calls on looped categories will not be truncated by numpy array dtype (eg: `<U4` array becoming `<U6` array)
* `biotite.structure.io.pdbx.convert._fill_annotations`
* ~~Add `typing` information to `_fill_annotations`~~
* …
> Structure module patches

- src/biotite/structure/io/ctab.py
- src/biotite/structure/io/mol/convert.py
- src/biotite/structure/io/mol/file.py
- tests/structure/test_mol.py
Hi
Related to modifications added in the [PR #381](https://github.com/biotite-dev/biotite/pull/381), I forgot to propagate `default_bond_type` to `MolFile.set_structure`. This PR aims to correct this
* `structure/io/ctab.py`: change type of  `default_bond_type` parameter to `BondType`  enum
* `src/biotite/structure/io/mol/convert.py`:  add `default_bond_type` parameter to generic `set_structure`
* `src/biotite/structure/io/mol/file.py`: add `default_bond_type` parameter to `MOLFile.set_structure`
*  `tests/structure/test_mol.py`: check `default_bond_type` fallback in `test_structure_conversion`
I hope it doesn't affect too much the initial design
> feat: propagate default_bond_type to molfile set_structure

- doc/apidoc.json
- src/biotite/structure/__init__.py
- src/biotite/structure/chains.py
- src/biotite/structure/residues.py
- src/biotite/structure/resutil.py
- tests/structure/test_chains.py
This PR adds further chain-level utilities analogous to residue-level utilities:
- `apply_chain_wise()`
- `spread_chain_wise()`
- `get_chain_masks()`
- `get_chain_starts_for()`
- `get_chain_positions()`
Common functionalities required by both `residues.py` and `chains.py` are moved into `resutil.py`.
Furthermore, a decreased residue ID is a further condition for a beginning chain as outlined in #389.
> Add more chain-level utitlities and change chain start condition

- src/biotite/sequence/align/matrix.py
Fixes typo in `dict_from_string()` that may lead to wrong score in substitution matrices with two different alphabets.
> Fix typo in matrix parsing

- src/biotite/structure/io/pdb/file.py
This PR presents an alternative solution as #401 to fix reading PDB files that have a line length smaller than 80 characters.
Here too short lines are padded with whitespace, when the PDB file is read.
> Pad PDB lines to 80 characters

- src/biotite/file.py
- src/biotite/structure/filter.py
- src/biotite/structure/io/mmtf/file.py
`Path` objects provide an OS-agnostic interface to the filesystem and are compatible with the built-in `open` function. However, using them in biotite raises an error and requires an explicit opening externally. I believe they should be handled the same way as the `str` in this case.
> support for Path objects

- src/biotite/structure/atoms.py
- src/biotite/structure/box.py
- src/biotite/structure/io/mmtf/__init__.py
- src/biotite/structure/io/mmtf/assembly.py
- src/biotite/structure/io/pdb/convert.py
- src/biotite/structure/io/pdb/file.py
- src/biotite/structure/io/pdbx/convert.py
- tests/structure/test_box.py
- tests/structure/test_mmtf.py
- tests/structure/test_pdb.py
This PR adds `get_assembly()` and `list_assemblies()` to `structure.io.pdb` and  `structure.io.mmtf` analogous to the functions in `structure.io.pdbx`.
In addtion, it adds `get_symmetry_mates()` to `structure.io.pdb`.
As foundation for the changes in `structure.io.pdb` `PDBFile` now also offers the `get_remark()` method to parse `REMARK`
records.
Furthermore, a `MemoryError` issue in `structure.repeat_box()`, that appeared on structures with associated `BondList`, was fixed.
> Read assemblies from PDB/MMTF files and symmetry mates from PDB files

- src/biotite/structure/io/pdb/file.py
This PR changes `biotite.io.pdb.PDBFile()` to make it write `CRYST1` records of length 80 instead of 70. This Problem was reported in https://github.com/biotite-dev/fastpdb/pull/4.
> Fix line length of 'CRYST1' record

- src/biotite/structure/box.py
- tests/structure/test_box.py
This PR refactors `remove_pbc()`:
- PCB removal is conducted for each molecule separately
- Not the first atom but the centroid of a molecule is placed within the box
- The `selection` can only be a boolean matrix
> Refactor `remove_pbc()`

- doc/apidoc.json
- doc/tutorial/src/database.py
- src/biotite/application/viennarna/rnafold.py
- src/biotite/database/rcsb/query.py
- tests/database/test_rcsb.py
This PR makes the following changes to `biotite.structure.database.rcsb` `search()` and `count()`:
- Add support for computational structures (e.g. from Alphafold DB) via the `content_types` parameter. This ability should work well with #465 .
- Add support for grouping via the new `group_by` and `return_groups` parameters. The type of grouping is selected via `Grouping` subclasses. This resolves #411 .
- Add support for ascending sorting with the `Sorting` class.
> Refactor interface to RCSB search API

- src/biotite/structure/io/pdbx/convert.py
- src/biotite/structure/io/pdbx/file.py
- tests/structure/data/molecules/CYN.cif
- tests/structure/data/molecules/HWB.cif
- tests/structure/data/molecules/TYR.cif
- tests/structure/test_mol.py
- tests/structure/test_pdbx.py
This PR adds the functions `structure.io.pdbx.get_component()` and `set_component()` to allow getting and setting chemical components from/to PDBx files via their `chem_comp` group of categories. Resolves #467 .
> Support chemical component parsing in `PDBxFile`

- src/biotite/structure/bonds.pyx
- src/biotite/structure/io/pdb/convert.py
- src/biotite/structure/io/pdb/file.py
- tests/structure/test_bonds.py
- tests/structure/test_pdb.py
This PR introduces the following changes:
- If the two `BondList`s in `BondList.merge()` have different bond types the parameter `BondList` takes precedence.
- `PDBFile` does give an appropriate `BondType`, if possible using the CCD
- A bug was fixed in `connect_via_distances()` and `connect_via_residue_names()` which may cause unexpected bonds to non-polymer residues.
> Tweaks to BondList merging

- src/biotite/sequence/align/kmeralphabet.pyx
- src/biotite/sequence/align/kmertable.pyx
- tests/sequence/align/test_kmeralphabet.py
This PR introduces a faster method for `create_kmers()` that uses the *k*-mer from the previous position to compute the next position. This way lopping over *k* is not necessary anymore as opposed to the current method.
The performance increase is clear (orange: naive, green: new method):
The following script was used to create the benchmarks:
```python
import time
import numpy as np
import biotite
import biotite.sequence as seq
import biotite.sequence.align as align
import matplotlib.pyplot as plt
LENGTH = 1_000_000
MAX_K = 12
N = 100
orig_durations = []
new_durations = []
sequence = seq.NucleotideSequence(ambiguous=False)
np.random.seed(0)
sequence.code = np.random.randint(len(sequence.alphabet), size=LENGTH)
k_values = np.arange(2, MAX_K+1)
for k in k_values:
kmer_alph = …
```
> Faster continuous k-mer decomposition

- src/biotite/sequence/io/fasta/convert.py
- tests/sequence/test_fasta.py
This PR implements the `seq_type` parameter as described in #477.
> Add manual seq type

- src/biotite/sequence/annotation.py
- tests/sequence/test_annotation.py
This PR is intended to fix a small bug I encountered when trying to index an `AnnotatedSequence` with a slice. 
Specifically, slicing forward from a start position without specifying a stop position was producing an error:
```python
sequence = NucleotideSequence("ATGGCGTACGATTAGAAAAAAA")
feature1 = Feature("misc_feature", [Location(1,2), Location(11,12)],
{"note" : "walker"})
feature2 = Feature("misc_feature", [Location(16,22)], {"note" : "poly-A"})
annotation = Annotation([feature1, feature2])
annot_seq = AnnotatedSequence(annotation, sequence)
```
---
Slicing with a stop but no start
```python
annot_seq[:16]
```
produces expected output
```
AnnotatedSequence(Annotation([Feature("misc_feature", [Location(11, 12, strand=Location.Strand.FORWARD, defect=Location.Defect.NONE), Location(1, 2, …
```
> Fix annotated sequence slicing bug

- src/biotite/database/pubchem/query.py
- src/biotite/database/rcsb/query.py
- tests/database/test_rcsb.py
This PR fixes the `database.rcsb` unit tests by updating tests results to the current state of the PDB.
> Update tests to current PDB version

- src/biotite/application/sra/__init__.py
- src/biotite/application/sra/app.py
- tests/application/test_sra.py
This PR increases the performance of `biotite.application.sra`:
- `prefetch` is called before `fasterq_dump`, as suggested [here](https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump).
- `FastaDumpApp` is added, which decreases computation time by writing as FASTA instead of a FASTQ file, which omits the scores.
> Increase performance of fetching via sra-tools

- src/biotite/database/pubchem/query.py
Due to frequent changes in the *PubChem* database doctests also frequently fail due to changes in returned CIDs and hence need to be adapated. In this PR most expected CIDs in the doctests are replaced by ellipses to make the doctests sustainably pass.
> Use ellipsis in doctests

- doc/examples/scripts/structure/base_pairs.py
- doc/examples/scripts/structure/peoe_visualization.py
- src/biotite/visualize.py
This PR addresses the changes in Matplotlib API in recent version:
- It replaces the `Transform.identity()` function when scaled letters (e.g. in a sequence logo) are plotted.
- It removes usage of deprecated Matplotlib functionalities in the example gallery.
> Support changes in Matplotlib API

- doc/apidoc.json
- doc/examples/scripts/sequence/gene_counts.py
- src/biotite/sequence/align/__init__.py
- src/biotite/sequence/align/cigar.py
- tests/sequence/align/test_cigar.py
> Support alignment conversion from/to CIGAR

- doc/conf.py
- src/biotite/database/rcsb/query.py
Currently the custom image scrapers do not work, as the config comments triggering them are filtered out automatically. This PR temporarily disables config comment removal until a better solution is found.
> Fix ignored image scrapers in gallery

- doc/examples/scripts/structure/ku_superimposition.py
- doc/examples/scripts/structure/md_analysis.py
- doc/examples/scripts/structure/peptide_assembly.py
- doc/tutorial/src/structure.py
- src/biotite/structure/basepairs.py
- src/biotite/structure/superimpose.py
- tests/database/test_rcsb.py
- tests/structure/test_superimpose.py
- Allow multiple `fixed` models
- Higher performance via more vectorization
- Removed some code duplication
Changes:
- Returns `AffineTransformation` instead of *transformation tuple*
- `superimpose_apply()` is deprecated in favor of AffineTransformation.apply()`
> Refactor `superimpose()`

- environment.yml
- pyproject.toml
Following the recommendation in https://github.com/numpy/numpy/issues/24300, the NumPy version is restricted to 1.x, as NumPy 2.0 will be published soon introducing some incompatibilities. In a second step Biotite will be prepared for NumPy 2.0 in #529.
> Restrict NumPy to 1.x

- .gitattributes
- .github/workflows/test_and_deploy.yml
- doc/install.rst
- src/biotite/structure/charges.pyx
- src/biotite/structure/info/atoms.py
- src/biotite/structure/info/ccd.py
- src/biotite/structure/info/ccd/README.rst
- src/biotite/structure/io/ctab.py
As explained in #541 and #542, these efforts to implement #530 brought more problems than benefits. Hence, the CCD will be put under regular Git version control again (as opposed to LFS) and a periodic update of the CCD will not be implemented.
> Put CCD subset under regular Git

- CONTRIB.rst
- src/biotite/structure/io/pdbx/cif.py
- src/biotite/structure/io/pdbx/convert.py
Two bugs:
1. #554 
2. fix bug in parsing oper_expression '(X0)(1-10,21-25)' from 1a34
> Fix two bugs in assembly generation

- src/biotite/sequence/align/cigar.py
- tests/sequence/align/test_cigar.py
> Add `include_terminal_gaps` parameter

- pyproject.toml
This PR restricts the required Python version to the scheme presented in [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html).
> Implement NEP 29

- src/biotite/structure/dotbracket.py
This PR fixes #556.
If no base pairs are found in `biotite.structure.base_pairs()`, `biotite.structure.dot_bracket_from_structure()` now returns a single empty string.
> Return empty dot bracket notation when no basepairs are found

- src/biotite/structure/superimpose.py
- tests/structure/test_superimpose.py
This PR adds the method `AffineTransform.get_matrix()` which allows getting the the superimposition transformation as 4x4 matrix.
> Get 4x4 transformation matrix from `AffineTransform`

- doc/apidoc.json
- src/biotite/structure/__init__.py
- src/biotite/structure/integrity.py
- src/biotite/structure/io/general.py
- src/biotite/structure/io/gro/file.py
- src/biotite/structure/io/pdb/file.py
- src/biotite/structure/repair.py
- tests/structure/test_generalio.py
- tests/structure/test_integrity.py
- tests/structure/test_pdb.py
- tests/structure/test_repair.py
This PR adds functions to repair malformed structures, namely `create_continuous_res_ids()` and `infer_elements()`.
Furthermore, `renumber_atom_ids()` and `renumber_res_ids()` are deprecated
> Add repair functions

- CONTRIB.rst
- src/biotite/sequence/annotation.py
- tests/sequence/test_annotation.py
Hi! This is an awesome project! Very nice work.
I stumbled upon a small bug. The `sorted_locs` variable is not used in `annotation.py`. The effect is that, when slicing with a feature with at least two locations on the minus strand, we get the wrong sequence.
I added a test to demonstrate the problem and fixed it.
> Fix slicing with annotation on minus strand

- doc/apidoc.json
- src/biotite/structure/repair.py
This PR adds `create_atom_names()` which can be used to obtain unique atom names for molecules.
> Add `create_atom_names()`

- tests/database/test_pubchem.py
We have an existing test against PubChem's API to retrieve ref ids.  Unfortunately, PubChem's responses will periodically change, breaking our test. This commit updates the test to handle those changes while still asserting the expected behavior of our query.
> Stabilize test_pubchem/test_search_simple

- pyproject.toml
Currently `Numpy 2.0` is installed along `Biotite` via pip. This causes issues with imports as version 2.0 is not officially supported by `Biotite` yet. This PR fixes this issue.
@padix-key are there any other potential places in the code that we need to adjust?
> `Numpy 2.0` is used when installing `Biotite`via pip.

- .github/workflows/test_and_deploy.yml
This is especially necessary, as the `macos-11` platform will be removed by GitHub end of June.
> Updated platform and tooling versions in CI

- CONTRIB.rst
- src/biotite/structure/atoms.py
This changes the hardcoded `Atom` `__repr__()` to a more general version that will additionally print custom added attributes.
**EDIT**: Fixes #602.
> Fix `Atom` `__repr__()` (#602)

- .github/workflows/test_and_deploy.yml
Currently the artifact name of the source distribution is `release-`. This PR renames it to `release-sdist`
> Fix artifact name for source distribution

- src/biotite/structure/bonds.pyx
- tests/structure/test_bonds.py
Fixes #609. By default an index is converted into an (order preserving) index array instead of a boolean mask now.
> Fix indexing with inverse slices

- environment.yml
**Description:**
Pinning mdtraj version between >=1.9.3, <1.10 in environment.yml to address compatibility issues. mdtraj 1.10 was recently release and seems to not be fully backwards compatible. 
Changes Made:
Updated environment.yml file to specify mdtraj version as >=1.9.3, <1.10 to address compatibility issues caused by recent updates.
Testing:
mdtraj 1.10 resulted in tests that relied on the TNGTrajectoryFile object in mdtraj  to fail. 
For example, tests/structure/test_trajectory.py
After pinning mdtraj to <1.10 all the tests passed successfully again.
> mdtraj 1.10 incompatibility

- src/biotite/structure/bonds.pyx
- tests/structure/test_bonds.py
after adding two bond list, `merged_bond_list` has wrong `_max_bonds_per_atom`.
```
import numpy as np
import biotite.structure as struc
bond_list1 = struc.BondList(2, np.array([(0,1)])) # max_bond_per_atom=1
bond_list2 = struc.BondList(3, np.array([(0,1),(0,2)])) # max_bond_per_atom=2
added_list = bond_list1 + bond_list2
print(f"{added_list._max_bonds_per_atom=}")
bonds, types = added_list.get_bonds(2)
print(f"{bonds.tolist()=} {types.tolist()=}")
print(f"{added_list.as_array().tolist()=}")
```
> fix a bug in add two bond lists.

- pyproject.toml
Fixes the `Using deprecated NumPy API` warning.
> Fix compilation warning about deprecated NumPy API

- src/biotite/structure/io/pdbx/cif.py
- tests/structure/test_pdbx.py
fix #570
use 3 regex patterns to match fields in one line for handle embed quote in mmcif file:
```
single_quote_pattern = r"('(?:'(?! )|[^'])*')(?:\s|$)"
double_quote_pattern = r'("(?:"(?! )|[^"])*")(?:\s|$)'
unquoted_pattern = r"([^\s]+)"
```
GPT4 explain single_quote_pattern:
> This regex `single_quote_pattern = r"('(?:'(?! )|[^'])*')(?:\s|$)"` is engineered to identify and extract substrings enclosed in single quotes from a larger text, with a particular sensitivity to handle internal apostrophes correctly. Let's dissect this expression to understand how it functions:
> 
> 1. **`'`**: This matches the opening single quote `'` of the target substring.
> 
> 2. **`(?: ... )`**: This is a non-capturing group, which means it groups the contained pattern parts without storing the matched …
> Handle embedded quote in mmcif

- environment.yml
- pyproject.toml
- src/biotite/sequence/align/permutation.pyx
Currently, both, NumPy run and build time dependencies are pinned to `2.x`. However, wheels build with `2.x` are still compatible with `1.x`: https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice.
Hence, this PR allows `1.x` as runtime dependency
> Relax runtime pin for NumPy

- .github/workflows/test_and_deploy.yml
- doc/switcher.py
- environment.yml
- src/biotite/sequence/io/genbank/file.py
- src/biotite/structure/io/pdbx/cif.py
- tests/structure/test_pdbx.py
Currently the DSSP tests are disabled in `next-major-release` due to some incompatibility between *libboost* and *DSSP*. This PR aims to solve this, by temporarily decreasing the Python version in the environment again.
Having a compatible DSSP software can be tackled later, e.g. by publishing https://github.com/PDB-REDO/dssp in `conda-forge`, as *libboost* is only required for testing (https://github.com/PDB-REDO/dssp/issues/50#issuecomment-1422767236):
> The requirements are limited, only zlib development files are needed. And boost is only required for building unit-tests.
Having an updated version of DSSP available would also solve #622.
> Adjust Python version to make it compatible with DSSP

- src/biotite/structure/atoms.py
- src/biotite/structure/io/pdbx/convert.py
- tests/structure/test_atoms.py
- tests/structure/test_pdbx.py
Currently the `AtomArray` annotation arrays are locked to their initial dtype. Usually this is no problem. However the PDBx format does not set a limit to string lengths, e.g. in `atom_site.comp_id` or `atom_site.label_atom_id`. Hence such potentially longer strings would be truncated to the dtype of the mandatory column, e.g. the chain ID `FOO_BAR` would become `FOO_` as the `chain_id` `dtype` is `U4`.
This PR changes this behavior: When `set_annotation()` is called a compatible dtype is searched. 
This PR replaces #640
>  Make dtype of mandatory annotation arrays dynamic

- src/biotite/structure/io/pdbx/bcif.py
- src/biotite/structure/io/pdbx/cif.py
- src/biotite/structure/io/pdbx/component.py
- tests/structure/test_pdbx.py
Currently, when CIF or BinaryCIF files are not created from scratch, but the files already contain untouched blocks or categories, the file is corrupted when written. This PR adds a test to cover this case and fixes the problem mentioned above.
Fixes #658.
> Fix invalid CIF/BCIF files created when file is edited

- benchmarks/structure/benchmark_pdbx.py
- doc/tutorial/structure/io.rst
- src/biotite/database/rcsb/query.py
- src/biotite/structure/io/pdbx/__init__.py
- src/biotite/structure/io/pdbx/bcif.py
- src/biotite/structure/io/pdbx/compress.py
- src/biotite/structure/io/pdbx/encoding.pyx
- tests/structure/test_pdbx.py
When data is set in `BinaryCIFFile` objects (e.g via `set_structure()`), a simple default encoding is used which does not compress the data. Although this is fast, the resulting files can be significantly larger. This PR introduces the `compress()` function, which takes an existing `BinaryCIF...` object and creates `BinaryCIF...` object with size-optimized encoding.
The resulting files are significantly smaller than the uncompressed ones and even quite a bit smaller than the ones originating from the PDB. The following example shows the size for `1L2Y`:
```
Original file from PDB:   199893 bytes
Uncompressed file:       1299713 bytes
File after `compress()`:  169448 bytes
```
>  Add `compress()` function to decrease the file size of BinaryCIF files 

- src/biotite/structure/atoms.py
Mini-PR to correct Docstrings for the `set_annotation` method under `_AtomArrayBase`.
> Docstrings for 'set_annotation': Remove 'None' as input type for 'array'.

- CONTRIB.rst
- src/biotite/structure/io/pdbx/convert.py
- tests/structure/test_pdbx.py
feat: allow writing out custom annotation to cif file
> Allow writing out custom annotation fields to cif files

- src/biotite/structure/io/pdbx/convert.py
When loading cif files, it is convenient to specify extra fields to be loaded (`b_factor, occupancy, charge`) without having to first inspect the `atom_site` record to see whether they exist. 
This PR implements this functionality by providing fallback default values for `b_factor` (`nan`) and `occupancy` (`1.0`) in cases where no annotation is given but the extra field is nontheless required. 
It also warns when formal charge is inferred, which currently happens silently assuming a fully uncharged structure `charge=0` everywhere.
> Allow loading computationally predicted cif files, which may not have certain custom annotations

- setup_ccd.py
Micro-PR to add `alt_atom_id` to Biotite's internal CCD:
**Why?** This is useful for resolving atom names in PDB files that do not use the standard atom ids, but use the alternative atom ids instead.
> Micro-PR to add `alt_atom_id` to Biotite's internal CCD

- tests/database/test_pubchem.py
- tests/test_doctest.py
Although the [Dynamic Request Throttling](https://pubchem.ncbi.nlm.nih.gov/docs/dynamic-request-throttling) is implemented in `biotite.database.pubchem`, it does not work properly, especially in the CI.
Hence, the PubChem tests are relaxed in this PR: A `RequestError` due to a busy PubChem server leads to a test skip and the PubChem doctests are omitted altogether.
> Allow failing PubChem tests due to busy server

- src/biotite/structure/io/pdbx/compress.py
- src/biotite/structure/io/pdbx/convert.py
This PR increases the speed in which PDBx files with structure + bonds written by Biotite can be read:
Currently, `pdbx.set_structure(include_bonds=True)` writes **all** inter-residue bonds, to be sure that all required bonds are written, because the [PDBx dictionary](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/struct_conn.html) describes the bonds that are stored in this category rather vaguely:
> Nonstandard residue linkage. The LINK records specify connectivity between residues that is not implied by the primary structure.
This means that the `struct_conn` category can become much larger than in the original from the PDB.
For parsing the `struct_conn` category again, each of its rows is matched against each row in `atom_site`. While this can be done in a fast …
> Omit 'standard' bonds when writing `struct_conn` category

- src/biotite/structure/io/pdbx/bcif.py
- src/biotite/structure/io/pdbx/cif.py
- src/biotite/structure/io/pdbx/component.py
Currently the CIF and BinaryCIF container classes use the default *mixin* implementation of `__contains__()`. However, this default implementation uses
```python
try:
self[key]:
except KeyError:
return False
return True
```
Hence, calling `__contains__()` actually gets the value, e.g. checking if a category name is in a CIF/BCIF block would automatically deserialize the category data. This counteracts the lazy deserialization behavior.
This PR explicitly implements `__contains__()` for all the mentioned container classes, checking only if a key is present and thus avoid the automatic deserialization.
> Avoid deserialization of PDBx data in `__contains__()`

- src/biotite/application/viennarna/rnaplot.py
- src/biotite/structure/io/pdbx/compress.py
- src/biotite/structure/io/pdbx/encoding.pyx
Currently, `pdbx.compress()` will always try integer packing on an integer array. However, this may explode, if the input array has large input values, as the number of bytes per element is `(value // 256) + 1` (for `byte_count=1` and `is_unsigned=True`).
This PR fixes this by estimating the integer packing output size before trying it.
> Do not try integer packing for huge values

- doc/tutorial/sequence/index.rst
- doc/tutorial/sequence/profiles.rst
- src/biotite/application/util.py
- src/biotite/database/uniprot/check.py
- src/biotite/database/uniprot/download.py
- src/biotite/database/uniprot/query.py
- src/biotite/sequence/align/alignment.py
- src/biotite/sequence/align/kmeralphabet.pyx
- src/biotite/sequence/align/matrix.py
- src/biotite/sequence/alphabet.py
- src/biotite/sequence/profile.py
- src/biotite/sequence/seqtypes.py
- tests/application/test_msa.py
- tests/sequence/align/test_matrix.py
- tests/sequence/test_seqtypes.py
- tests/test_repr.py
This PR adds functionality for creating positional substitution matrices, i.e. matrices that have a score for each position in a sequence. This allows position-specific sequence alignments, such as algorithms like TM-align or sequence profile alignments using a `SequenceProfile`.
> Add positional substitution matrices

- src/biotite/structure/io/pdbx/cif.py
- tests/database/test_rcsb.py
- tests/structure/io/test_pdbx.py
This is an attempt to update _split_one_line function to avoid usage of 'whitespace' parameter and approximation made for '_atom_site' CIF block.
Performance have to be approved with a CI run.
> Update _split_one_line and remove whitespace parameter

- src/biotite/structure/atoms.py
A tiny fix, to allow counting `nan` values as equal in annotations. This makes sense in cases where annotations are flagged as not available (e.g. b_factor = `nan`).
> fix: allow matching `nan` values in annotations (e.g. when b_factors are set to `nan`)

- doc/apidoc.json
- src/biotite/structure/atoms.py
- src/biotite/structure/bonds.pyx
- tests/structure/test_atoms.py
- tests/structure/test_bonds.py
This PR adds the `concatenate()` function that allows efficient concatenation of more than two `AtomArray` or `AtomArrayStack` objects.
> Support concatenation of more than two `AtomArray` objects

- src/biotite/structure/__init__.py
- src/biotite/structure/io/pdb/convert.py
- src/biotite/structure/io/pdb/file.py
- src/biotite/structure/io/pdbx/convert.py
- tests/structure/io/test_pdb.py
- tests/structure/io/test_pdbx.py
Biotite doesn't currently distinguish between the chains produced by symmetry operations on a given asym unit in an assembly.
This can make certain selection operations slightly inconvenient (e.g. getting residue starts of a specific chain etc.) and is inconsistent with the chain naming convention employed by the PDB in assembly .cif files.
This PR follows the PDB convention of appending a '-<oper_id>' to the chain ids.
> disambiguate assembly chains by appending assembly id

- src/biotite/structure/io/pdbx/cif.py
This PR introduces a shortcut for CIF line splitting (the speed limiting step of `CIFFile`) if the line contains no quoted value. This is the case for almost all lines.
> Use fast whitespace split if no quoted values are in line

- .github/workflows/test_and_deploy.yml
- README.rst
- doc/contribution/deployment.rst
- doc/install.rst
- pyproject.toml
- src/biotite/setup_ccd.py
- src/biotite/structure/info/ccd.py
- tests/test_modname.py
currently the setup_ccd.py script has to be run from a clone of the repo. this creates a command-line utility to run the ccd update directly from the pip installed package itself. i think this simplifies dependency management for downstream projects quite a bit
> Enable CCD update from installed package

- src/biotite/sequence/align/banded.pyx
Currently `align_banded()` may return local alignments even if `local=False` under rare circumstances.
The problem was that band diagonals are trimmed to the size of the sequences (just to save memory), but under this cicumstances the band width is not updated. This allowed the trace to 'escape' the alignment band for low-scoring alignments leading to a premature traceback termination and thus local alignments instead of semi-global ones.
> Fix wrong band width calculation under some circumstances

- src/biotite/structure/io/pdb/file.py
- tests/structure/io/test_pdb.py
Added `get_space_group()` and `set_space_group()` methods as discussed in #689 to support space group and Z value reading/writing for (deprecated) PDB files.
> Add support for space group information when reading and writing pdb files

- src/biotite/structure/io/pdbx/convert.py
The [`label_entity_id`](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_atom_site.label_entity_id.html) is a standard category in cif files that relates the asym_id to the entity_id in entity_poly. 
Currently, when writing out an AtomArray as cif file, entity_id's are always determined anew, giving new chains new entity id's even when they are actually the same entity (try e.g. `5ocm`). This tiny PR allows to pass on the `label_entity_id` to writing out the structure. This category can already be loaded in AtomArrays via the `extra_fields` keyword argument.
> feat: allow setting the `label_entity_id` from the AtomArray, if annotated

- src/biotite/structure/info/atoms.py
- src/biotite/structure/io/pdbx/convert.py
- tests/structure/test_info.py
There are a number of ligands/residues in the CCD with missing coordinates that cannot be retrieved now with `structure.info.residue` due to a ValueError that is raised twice and not excepted the second time. Relative to v0, this is new behavior.
This allows these residues to be returned from the second attempt with nans where missing.
> fix: allow ccd residues with missing coords

- src/biotite/structure/tm.py
The previous error message is a bit vague, as it requires knowledge of the algorithm itself. The new message elucidates the cause better.
> Improve error message in `align_structural_homologs()`

- src/biotite/structure/bonds.pyx
- src/biotite/structure/io/mol/ctab.py
- src/biotite/structure/io/pdbx/convert.py
- tests/structure/io/test_mol.py
The kekulized form of aromatic bonds (i.e. their representations as single, double or triple bonds) is a visualization artifact: Chemically aromatic bonds have no bond order, but the pi-elections are delocalized in the entire pi-system.
For this reason I think it makes sense to lift the restriction to assign a bond to either of `AROMATIC_SINGLE`, `AROMATIC_DOUBLE` or `AROMATIC_TRIPLE`, but to allow a generic `AROMATIC` as well. Although, this might lead to some limitations in visualization, there are some advantages
- Models predicting aromatic bonds do not necessarily need to know the kekulized form.
- Some software does not internally represent aromatic bonds in kekulized form (e.g. RDKit).
- SDF and PDBx support generic aromatic bonds as well.
> Add generic aromatic bond

- src/biotite/structure/celllist.pyx
Currently the `coord` given to `CellList.get_atoms()` and `CellList.get_atoms_in_cells()` are not checked, whether they are finite. Although bounds checks are conducted (no out of bounds memory access is possible), it is still possible that atoms from wrong cells are returned. This PR adds a check for non-finite values.
> Check that finite values are given as query to `CellList` 

- src/biotite/structure/chains.py
- src/biotite/structure/compare.py
- src/biotite/structure/residues.py
- tests/structure/test_compare.py
This PR adds to parameters to `lddt()`:
- `exclude_same_chain`: Excludes contacts within the same chain
- `filter_function`: Allows passing a custom function to filter even more contacts
> Allow more custom contact filtering in `lddt()`

- environment.yml
- src/biotite/interface/rdkit/mol.py
This PR reflects that `Conformer.SetPositions()` was added in RDKit `2024.09.1`.
> Add proper RDKit version constraints

- src/biotite/interface/rdkit/mol.py
Here's an attempt at grouping the standard annotations under the appropriate RDKit annotation as discussed here https://github.com/biotite-dev/biotite/pull/736#discussion_r1928414116
Let me know what you think -- what I'm not 100% happy with yet is that 
(1) python-iterating over atoms seems inefficient, I wonder if there's an array-like API in RDKit and 
(2) I'm currently not tracking whether an annotation was explicitly set because it was present in the original AtomArray or whether it's filling in the default value. Doing this seems non-trivial for rdkit methods which change the underlying mol -- unless maybe we add a bool property that tracks if an annotation exists?
> feat: use rdkit internal PDBResidueInfo for standard annotations

- src/biotite/structure/atoms.py
The `structure.array()` method truncates any string-based annotations to an arbitrary length of string. i.e. you can end up with
```
atoms[1000] --> Atom(..., str_annot="111", ...)
atoms[1000].str_annot.dtype --> dtype('<U3')
array = structure.array(atoms)
array[1000] --> Atom(..., str_annot="1", ...)
array[1000].str_annot.dtype --> dtype('<U1')
```
The culprit is this
```array.add_annotation(name, dtype=type(atoms[0]._annot[name]))```
is using the first atom in the array, which is often the shortest, to determine the dtype of the whole array. This is particularly problematic when processing cif columns that contains string representations of ids. Instead, we need to find the maximum length across the atom list to ensure no truncations occur.
> bug fix: string truncation in AtomArray annotations

- doc/apidoc.json
- doc/references.bib
- src/biotite/structure/__init__.py
- src/biotite/structure/rings.py
- tests/structure/test_rings.py
This PR adds the `find_aromatic_rings()` and `find_stacking_interactions()` functions to `biotite.structure`, that can be used to identify atoms that are part of aromatic rings and find pi-stacking interactions between them, respectively.
> Add functionalities related to aromatic rings

- src/biotite/structure/tm.py
This PR fixes a small deviation from the [TM-align paper](https://doi.org/10.1093/nar/gki524). The filtering of anchor residues is now only performed in the iterative refinement (step 3).
> Do not filter anchors in step 2 of `superimpose_structural_homologs()`

- doc/conf.py
- doc/extensions.rst
- doc/tutorial/interface/index.rst
- doc/tutorial/interface/openmm.rst
- doc/tutorial/structure/index.rst
- doc/tutorial/structure/trajectories.rst
- environment.yml
- src/biotite/interface/openmm/__init__.py
- src/biotite/interface/openmm/state.py
- src/biotite/interface/openmm/system.py
- tests/interface/test_openmm.py
As described in #709, this PR adds an interface to the *OpenMM* molecular simulation toolkit.
The code is taken and adapted from [`biotite-dev/molmarbles`](https://github.com/biotite-dev/molmarbles/). Afther this PR is merged, [`biotite-dev/molmarbles`](https://github.com/biotite-dev/molmarbles/) will be archived.
> Integrate `openmm` into `biotite.interface.openmm`

- doc/tutorial/interface/rdkit.rst
- src/biotite/interface/rdkit/mol.py
- tests/interface/test_rdkit.py
This parameter in `interface.rdkit.to_mol()` defines whether hydrogen should be explicitly or implicitly included in the created `Mol`
> Add `explicit_hydrogen` parameter

- src/biotite/structure/segments.py
This tiny PR speeds up all uses of `spread_X_wise` in the codebase by replacing the python for-loop through numpy's vectorized analog. For small structures the performance improvement is negligible, but for large structures or if this method is called many times (e.g. in ML pipelines) this gives a slight boost.
> speed up `spread_X_wise`

- src/biotite/structure/io/pdbx/cif.py
Fixes e.g. the following snippet:
```python
import biotite.structure.io.pdbx as pdbx
import biotite.structure as struc
import biotite.database.rcsb as rcsb
pdbx_file = pdbx.CIFFile.read(rcsb.fetch("1aki", "cif", "."))
for block in pdbx_file.values():
print(block)
```
> Add block name to deserialized blocks

- doc/apidoc.json
- src/biotite/structure/io/pdbx/convert.py
- tests/structure/io/test_pdbx.py
Added get_sse function. Each residue annotated as 'a' for alpha, 'b' for beta, or 'c' for coil
> Support extraction of secondary structure elements from PDBx files

- src/biotite/interface/rdkit/mol.py
- src/biotite/structure/io/pdbx/convert.py
- tests/structure/io/test_pdbx.py
When obtaining an AtomArray using `pdbx.get_structure()`, the invoked `_find_matches()` function generates a `[N_struct_conn_col, N_struct_conn_row, N_atom]` matrix. In cases where a CIF file contains numerous atoms and numerous inter-residue bonds, this can lead to a significant increase in memory usage. For example, for PDB ID 7Y4L, memory consumption can reach up to 100GB, and it takes approximately 450 seconds to run `pdbx.get_structure()`.
This PR modifies the implementation of `_find_matches()` to address and prevent this issue. With the updated code, processing 7Y4L requires less than 1.5GB of memory, and the runtime is reduced to approximately 45 seconds.
> Optimize memory utilization of `get_structure()`.

- .github/workflows/test_and_deploy.yml
- doc/examples/scripts/structure/modeling/trajectory_sse.py
- doc/examples/scripts/structure/protein/transketolase_sse.py
- doc/tutorial/application/blast.rst
- doc/tutorial/application/dssp.rst
- environment.yml
- src/biotite/sequence/io/genbank/file.py
Due to the ongoing problems with Conda DSSP builds, this PR bypasses the usage of `DsspApp` for now:
- `dssp` is removed from Conda environment.
- DSSP tutorial is not run but displayed statically (like the *NCBI BLAST* tutorial does for the sake of run time).
- Affected examples use other means to get the secondary structure for now.
> Bypass DSSP in tests and documentation

- doc/extensions.rst
This PR adds [pepp'r](https://peppr.vant.ai/) to the list of extension packages in the docs.
> Add pepp'r to extension packages

- src/biotite/structure/box.py
- src/biotite/structure/chains.py
- src/biotite/structure/residues.py
- src/biotite/structure/segments.py
`AtomArray` object from biological assemblies and unit cells set the `sym_id` annotation. This PR takes `sym_id` also into consideration when determining chain and residue starts. This is especially useful in the edge case, where a unit cell/assembly chain contains only a single residue/chain, as this still allows for distinguishing different molecules.
> Check `sym_id` for determining residue and chain starts

- pyproject.toml
- src/biotite/interface/openmm/__init__.py
- src/biotite/interface/pymol/__init__.py
- src/biotite/interface/rdkit/__init__.py
- src/biotite/interface/version.py
If *PyMOL* is not installed, the error message `cannot import name 'Atom' from 'chempy'` (#787) is shown. This can be quite confusing, as it does not directly point to the missing *PyMOL* installation.
This PR adds the `require_package()` function that outputs clear error messages for missing dependencies and uses it across all `biotite.interface` subpackages.
> Add proper error message when interface dependency is missing

- .github/workflows/test_and_deploy.yml
- pyproject.toml
Compliant with [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table), this PR sunsets support for Python 3.10.
> Remove support for Python 3.10

- environment.yml
Due to [Anaconda licensing changes](https://www.anaconda.com/blog/update-on-anacondas-terms-of-service-for-academia-and-research) packages from Anaconda are only available without license for organizations with less than 200 members.
To avoid accidental license violations by users using the Biotite development environment (i.e. the `environment.yml`), the anaconda channel is removed from this environment. This should not be a problem, as all dependencies are also available in `conda-forge` or `bioconda`.
> Remove `anaconda` channel from development environment

- .github/workflows/test_and_deploy.yml
- pyproject.toml
The `pyproject.toml` uses a new format for specifying the license as described [here](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license).
> Update license metadata

- src/biotite/structure/io/pdbx/compress.py
- src/biotite/structure/io/pdbx/encoding.pyx
- tests/structure/io/test_pdbx.py
This PR ensures more strictly for each `pdbx.Encoding` that only compatible values can be cast into the target dtype. These checks revealed two additional issues:
- Currently non-finite values (Infinity, NaN) are not properly handled by `compress()` and thus `compress()` still converts them into integers (`0`). In this PR `compress()` does not try `FixedPointEncoding` if any value in the input array is non-finite.
- `DeltaEncoding.encode()` may encounter Integer underflows, if the input dtype is unsigned, as `np.diff()` does not return a signed dtype but keeps the input dtype instead. As `DeltaEncoding.decode()` performs the reverse operation (encountering an integer overflow) the value becomes correct again, which was confirmed by the tests. So in summary a BinaryCIF file created by …
> Stricter dtype checks during BinaryCIF encoding

- .github/workflows/test_and_deploy.yml
Currently on Biotite release the complete docs are built, which is a time consuming process and may intermittently fail due to request failures to different databases. To avoid that the already built examples/tutorials need to be rerun, if such failures happen, this PR adds a cache for the docs: When the job is rerun, the partially built docs are restored from cache and only the failed parts need to be run again.
> Cache partially build docs in CI

- src/biotite/interface/pymol/object.py
Currently an exception is raised when the `selection` parameter of `PyMOLObject` method is supplied with a slice. This PR fixes this.
> Fix slice indices for PyMOL object selection

- src/biotite/structure/compare.py
- tests/interface/test_openmm.py
Currently `lddt()` raises a warning if the atoms are within the threshold distance of each other in the reference structure. This PR fixes this.
> Avoid warning in case of no contact in structure

- src/biotite/structure/info/atoms.py
This PR caches subsequent calls of `structure.info.residue()` to make a common application like [creating a chain from scratch](https://www.biotite-python.org/latest/examples/gallery/structure/protein/peptide_assembly.html) more efficient, as many calls to `pdbx.get_component()` accumulate quite some run time.
To keep the memory footprint still very low an LRU cache with maximum size 100 is used. This is enough to cache the number of different residues to build polymer chains (peptides, nucleic acids, saccharides), but will not blow up the memory requirements for use cases where large parts of the CCD are parsed.
> Use LRU cache for `structure.info.residue()`
