src/biotite/sequence/align/alignment.py
tests/sequence/test_align.py

- get_codes()
- get_symbols()
- get_sequence_identity()
- score()

Useful functions for Alignment objects

---

src/biotite/structure/sasa.pyx

This PR increases the default point number from 100 to 1000 and improves the performance by fixing a small bug.

SASA: performance improvement and increase of default point number

---

doc/examples/scripts/sequence/ws_genome_search.py
doc/examples/scripts/structure/diameter.py
doc/examples/scripts/structure/md_analysis.py
doc/examples/scripts/structure/ramachandran.py
src/biotite/sequence/align/alignment.py
src/biotite/sequence/graphics/alignment.py
src/biotite/sequence/seqtypes.py

Fixed typos and added examples

Enhanced documentation

---

src/biotite/sequence/graphics/alignment.py

Fixing custom color schemes for alignment visualizations

---

setup.py

Setup: Numpy and Cython are only imported, if Cython files are present

---

doc/examples/scripts/sequence/lexa_conservation.py
src/biotite/application/blast/webapp.py

- `BlastWepApp` indicates when URI is too long
- Fixed *LexA* example

Improvements for Biotite 0.10.1

---

src/biotite/structure/io/gro/file.py
tests/structure/test_gro.py

This is a fix for #96 . I basically copy-pasted the solution you used for overflowing pdb files and wrote an appropriate unit test.
Cheers

fix gro id overflow - fixes #96

---

doc/examples/scripts/sequence/hcn_hydropathy.py
doc/examples/scripts/sequence/lexa_conservation.py
doc/examples/scripts/sequence/region_visualization.py
doc/examples/scripts/sequence/sw_genome_search.py
doc/examples/scripts/structure/transketolase_sse.py
doc/tutorial_src/sequence.py
src/biotite/sequence/alphabet.py
src/biotite/sequence/annotation.py
src/biotite/sequence/io/genbank/__init__.py
src/biotite/sequence/io/genbank/annotation.py
src/biotite/sequence/io/genbank/file.py
src/biotite/sequence/io/genbank/metadata.py
src/biotite/sequence/io/genbank/sequence.py
src/biotite/structure/io/pdbx/file.py
tests/sequence/test_annotation.py
tests/sequence/test_genbank.py

This PR introduces a massively changed GenBank API:
The `GenBankFile` class provides a low-level interface for getting and setting the lines corresponding to the field names. Based on these methods the module-level utility functions are used to obtain more useful objects from a `GenBankFile` instance, for example annotations and sequences.
The utility functions allow setting the *LOCUS*, *FEATURES* and *ORIGIN* fields of a GenBank file, enabling write support for this file type.
Furthermore this PR contains minor fixes associated with `Annotation` objects.

Revamped interface for GenBank files

---

src/biotite/sequence/alphabet.py
src/biotite/sequence/codec.pyx
tests/sequence/test_alphabet.py
tests/sequence/test_sequence.py

This PR massively increases the performance of the encoding of symbols into the sequence code and vice versa for the `LetterAlphabet` class

Increased performance of alpahet encoding

---

src/biotite/sequence/codon.py
src/biotite/sequence/seqtypes.py
tests/sequence/test_codon.py
tests/sequence/test_seqtypes.py

The PR introduces a new internal storage of codons in The `CodonTable` class. Using a radix based approach the codons are saved as `ndarray`. Hence the translation can be vectorized.

More efficient CodonTable

---

src/biotite/sequence/phylo/nj.pyx

This PR adds Cython compiler flags for neighbor joining in order to increase performance.

Increased perfromance for neighbor joining

---

src/biotite/structure/io/pdb/file.py

This PR adds a new, more precise check for equal amount of atoms in each model.

Adding more precise check for PDB files

---

src/biotite/structure/atoms.py

Better error message for 'array()' and 'stack()' function

---

src/biotite/structure/compare.py
tests/structure/test_compare.py

Fixing #146

---

src/biotite/structure/atoms.py
tests/structure/test_atoms.py

Adds an additional property to AtomArrays and Stacks similar to np.shape.

add shape paramenter

---

src/biotite/database/rcsb/download.py
src/biotite/sequence/io/fasta/file.py
src/biotite/sequence/io/fastq/file.py
tests/database/test_rcsb.py

Implementing #156

---

doc/apidoc.json
doc/tutorial_src/application.py
doc/tutorial_src/database.py
doc/tutorial_src/introduction.py
doc/tutorial_src/sequence.py
doc/tutorial_src/structure.py
src/biotite/structure/atoms.py
src/biotite/structure/superimpose.py
src/biotite/structure/transform.py
tests/structure/test_superimpose.py
tests/structure/test_transform.py
tests/test_doctest.py

This PR adds two new functions:
- `rotate_about_axis()`
- `align_vectors()`
Now also the existing transformation functions
- `translate()`
- `rotate()`
- `rotate_centered()`
accept directly coordinates as input and have a consistent rotation direction.
Furthermore, there is a new `Structure manipulation` subsection in the tutorial.

Adding new transformation functions and extending the exisiting ones

---

LICENSE.rst
doc/apidoc.py
doc/conf.py
src/biotite/structure/compare.py
src/biotite/visualize.py

...and updated some docstrings.

Fixing API documentation for functions

---

doc/apidoc.json
src/biotite/structure/filter.py
tests/structure/test_filter.py

Added the function `biotite.structure.filter_nucleotides`
Filters for the most common nucleotides in an `AtomArray/AtomArrayStack`

Added filter for Nucleotides

---

src/biotite/structure/filter.py
src/biotite/structure/io/pdbx/convert.py
tests/structure/data/4gxy.cif
tests/structure/data/4gxy.pdb
tests/structure/data/README.rst
tests/structure/test_filter.py
tests/structure/test_pdbx.py

Added nucleotide Support for `biotite.structure.io.pdbxfile.get_sequence`

Enabled pdbx.get_sequence() to read nucleotides

---

src/biotite/structure/bonds.pyx

Fixing #184

---

src/biotite/structure/bonds.pyx
tests/test_doctest.py

Fixes #179

---

src/biotite/structure/hbond.py

Raise warning in 'hbond()' for structures without hydrogen atoms

---

src/biotite/structure/info/atoms.py

Fix charge annotation in 'info.residue()'

---

doc/apidoc.json
src/biotite/structure/residues.py

This PR increases the performance of the following residue-level functions by a factor of ~5x:
- `get_residue_starts_for()`
- `get_residue_masks()`
Furthermore it adds the function
- `get_residue_positions()`

Improve resiude-level functions

---

src/biotite/structure/basepairs.py
src/biotite/structure/bonds.pyx
tests/structure/test_bonds.py

This PR introduces several new functions for `structure.BondList`:
- `get_all_bonds()`
- `adjacency_matrix()`
- `bond_type_matrix()`
Furthermore, the following improvements are included:
- Fixed indexing behavior for index arrays
- Extended doctest examples

New functions for 'BondList'

---

src/biotite/structure/atoms.py

Currently, it only tries to delete non-existent annotations.

Fix del_annotation.py

---

src/biotite/structure/charges.pyx
tests/structure/test_charges.py

This PR increases the performance of the `partial_charges()` function via *Cythonization*.

Increase performance of 'partial_charges()'

---

CONTRIB.rst
src/biotite/sequence/alphabet.py
src/biotite/sequence/seqtypes.py
src/biotite/sequence/sequence.py
tests/sequence/test_seqtypes.py
tests/test_repr.py

Partly fixes #290 
- NucleotideSequence
- ProteinSequence
- GeneralSequence
- Alphabet
- AlphabetLetter
@padix-key I'm not quite sure how to implement method `__repr__` for abstract base class `Sequence`

Part of issue 290

---

src/biotite/sequence/align/alignment.py
src/biotite/sequence/align/matrix.py
src/biotite/sequence/annotation.py
src/biotite/sequence/codon.py
src/biotite/structure/atoms.py
tests/test_repr.py

Fixes #290
New __repr__ method for classes:
- CodonTable
- Alignment
- SubstitutionMatrix
- Location
- Feature
- Annotation
- AnnotatedSequence
- Atom
Classes AtomArray and AtomArrayStack can use __repr__ method from respective superclass
@padix-key I think for classes CodonTable and SubstitutionMatrix are new __eq__ and __ne__ methods necessary? What do you think?

Issue 290 Part 2

---

src/biotite/structure/io/general.py
tests/structure/test_generalio.py

Here is a proposal for a way to filter templates based on `atom_i` in `io.load_structures`

Resolves #308

---

src/biotite/sequence/align/alignment.py
src/biotite/sequence/profile.py
tests/sequence/test_profile.py

This PR decreases the runtime of `sequence.align.get_codes()` and `sequence.align.get_symbols()` by replacing loops with vectorized operations. Consequently, the performance of `sequence.SequenceProfile.from_alignment()` is also improved.
Furthermore, this PR makes cosmetic changes to the `sequence.profile` module.

Performance improvement of 'get_code()' and 'get_symbols()'

---

.github/workflows/test.yml
appveyor.yml
doc/examples/scripts/sequence/color_schemes_protein.py
doc/examples/scripts/sequence/genome_comparison.py
doc/examples/scripts/sequence/local_alignment_statistics.py
doc/examples/scripts/structure/leaflet.py
doc/references.bib
doc/tutorial/src/sequence.py
src/biotite/sequence/align/__init__.py
src/biotite/sequence/align/kmertable.pyx
src/biotite/sequence/align/localgapped.pyx
src/biotite/sequence/align/localungapped.pyx
src/biotite/sequence/align/multiple.pyx
src/biotite/sequence/align/pairwise.pyx
src/biotite/sequence/align/statistics.py
tests/sequence/align/test_localgapped.py
tests/sequence/align/test_pairwise.py
tests/sequence/align/test_statistics.py

This PR adds the following improvements to the `biotite.sequence.align` subpackage:
- Adding `max_table_size` parameter for `align_local_gapped()`
- Adding `EValueEstimator` for easy calculation of E-values from alignment scores
Furthermore two examples for E-value calculation and genome comparison are added to the gallery.

Improvements for the homology search toolbox

---

CONTRIB.rst
src/biotite/structure/transform.py
tests/structure/test_transform.py

The function translates atoms to the origin and rotates the molecule
such that the variance decreases from x to z. Included a basic test.

Added orient_principal_components

---

src/biotite/structure/geometry.py
src/biotite/structure/superimpose.py
tests/structure/test_superimpose.py

Removed duplicate code handling different cases with AtomArray versus AtomArrayStack input.
Fixed random bug in geometry.py that would have affected error handling.

Cleaned up superimpose code

---

src/biotite/structure/hbond.py
tests/structure/test_hbond.py

'hbond()' uses BondList to find bonded hydrogen atoms

---

src/biotite/database/rcsb/query.py
src/biotite/structure/hbond.py
tests/database/test_rcsb.py

Support for RCSB PDB search API v2

---

src/biotite/database/rcsb/query.py

- Remove 'node_id'
- Fix negation

Amendment to #408

---

src/biotite/structure/io/trajfile.py
tests/structure/test_trajectory.py

This PR adds the optional `stack_size` parameter to `TrajectoryFile.read_iter()` and `TrajectoryFile.read_iter_structure()` to allow reading multiple frames at one. Fixes #419.

Support stack-wise iteration over trajectory files

---

src/biotite/structure/io/pdb/file.py

fix(pdbparsing): parse "+X" and "X+" charges

---

src/biotite/structure/basepairs.py

This PR fixes the typo pointed out in #432.

Fix typo in base_stacking()

---

doc/apidoc.json
src/biotite/application/tantan/app.py
src/biotite/sequence/align/kmertable.pyx
src/biotite/sequence/alphabet.py
tests/application/test_tantan.py
tests/sequence/test_alphabet.py

Fixes #445. This PR enables the user to give `TantanApp` multiple input sequences to increase the computation speed. Furthermore it adds the convient `common_alphabet()` function to find the common alphabet in a list of alphabets.

`TantanApp` is able to process multiple sequences in a single run.

---

tests/database/test_rcsb.py

This PR adapts the expected test output with actual current number of respective entries in the PDB.

Fix RCSB PDB test

---

src/biotite/structure/io/pdb/file.py
tests/structure/test_pdb.py

This PR adds `PDBFile.get_b_factor()` analogous to `PDBFile.get_coord()`. Furthermore, the indices of model and atom records are now indexed when the file is read, which removes a number of code duplications. Resolves #449 .

Refactor `PDBFile` and add `get_b_factor()`

---

doc/apidoc.json
doc/examples/scripts/structure/alkane_isomers.py
doc/index.rst
doc/references.bib
src/biotite/database/pubchem/__init__.py
src/biotite/database/pubchem/download.py
src/biotite/database/pubchem/error.py
src/biotite/database/pubchem/query.py
src/biotite/database/pubchem/throttle.py
src/biotite/database/rcsb/download.py
src/biotite/database/rcsb/query.py
src/biotite/structure/filter.py
src/biotite/structure/io/ctab.py
src/biotite/structure/io/mol/file.py
src/biotite/structure/io/pdbx/convert.py
tests/database/test_pubchem.py
tests/test_doctest.py

This PR adds an interface to the *PubChem* database for compound searching and structure download.
Furthermore this PR fixes the format of the header and count lines in .mol files.

Add PubChem interface

---

src/biotite/database/pubchem/query.py
src/biotite/database/rcsb/query.py
tests/database/test_pubchem.py
tests/database/test_rcsb.py

This PR changes tests and doctests to reflect changes in the PDB and PubChem databases, leading to different output than before.

Adapt tests to changes in PDB and PubChem databases

---

environment.yml
pyproject.toml
src/biotite/sequence/align/banded.pyx
src/biotite/sequence/align/localgapped.pyx
src/biotite/sequence/align/pairwise.pyx
src/biotite/sequence/align/tracetable.pxd
src/biotite/sequence/align/tracetable.pyx
src/biotite/structure/io/pdb/hybrid36.pyx

Move to Cython 3.x

---

src/biotite/structure/rdf.py
tests/structure/test_rdf.py

RDF: AtomArray + (3,3)-shaped box as arguments.

---

src/biotite/application/application.py

Provide a clearer error message for the scenario shown in #501 .

Clearer error message, if `Application` instance method is called without instance

---

.github/workflows/test_and_deploy.yml
doc/apidoc.json
doc/conf.py
doc/contribute.rst
doc/key.py
doc/tutorial.py
src/biotite/database/entrez/__init__.py
src/biotite/database/entrez/check.py
src/biotite/database/entrez/download.py
src/biotite/database/entrez/key.py
src/biotite/database/entrez/query.py

This PR adds support for NCBI API keys (https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/) and uses them in the gallery and tutorial build.

Support NCBI API keys

---

environment.yml

This MR introduces categories and alphabetical sorting into the `environment.yml`.

Structure `environment.yml`

---

.github/workflows/test_and_deploy.yml

This PR repairs the CI by fixing the upload the of the documentation artifact

Fix artifact upload

---

doc/examples/scripts/structure/glycan_visualization.py
doc/references.bib
src/biotite/structure/io/pdbx/convert.py

Fix minor issues in documentation

---

src/biotite/structure/info/atoms.py
src/biotite/structure/io/pdbx/convert.py

Add more descriptive error message for `residue()`

---

src/biotite/structure/io/pdbx/cif.py
src/biotite/structure/io/pdbx/convert.py
tests/structure/test_pdbx.py

Fix setting empty columns

---

src/biotite/structure/io/pdb/file.py
tests/structure/test_pdb.py

Ensure PDB columns are not exceeded

---

src/biotite/structure/integrity.py

Just some very minor typo fixes.

fix: typos

---

src/biotite/structure/bonds.pyx

Fix bond inference for structures with insertion codes

---

src/biotite/structure/io/mol/sdf.py

This also allows MOL files to be read with `SDFile` (although this will emit a warning).

Allow SD files without terminal delimiter

---

doc/tutorial/structure/index.rst
environment.yml
pyproject.toml
src/biotite/sequence/align/alignment.py
src/biotite/sequence/align/kmertable.pyx
src/biotite/sequence/align/permutation.pyx
src/biotite/sequence/align/selector.pyx
src/biotite/sequence/alphabet.py
src/biotite/sequence/codon.py
src/biotite/structure/filter.py

NumPy 2.0 will be released soon (https://github.com/numpy/numpy/issues/24300), bringing some deprecated functionalities and breaking changes with it. This PR aims to make Biotite ready for usage with NumPy 2.0.

Update to NumPy 2.0

---

doc/examples/scripts/sequence/misc/color_schemes_protein.py
src/biotite/sequence/graphics/alignment.py
src/biotite/sequence/graphics/logo.py

Use 'flower' as default color scheme

---

pyproject.toml

Set the PyPI classifier `Development Status` to `5 - Production/Stable`.

Set Biotite package to stable

---

.github/workflows/test_and_deploy.yml
benchmarks/conftest.py
benchmarks/structure/benchmark_pdbx.py
doc/contribution/testing.rst
environment.yml
pyproject.toml

This PR introduces CodSpeed for benchmarking als already done for https://github.com/biotite-dev/fastpdb. The benchmark code is put into the `benchmarks` directory. For now only a few initial benchmarks are added, but as the documentation now specifies, new benchmark functions should be added for code changes that might significantly affect performance.

Use CodSpeed for benchmarking

---

src/biotite/structure/filter.py

fix: make altlocs deterministic

---

src/biotite/structure/io/pdbx/cif.py
tests/structure/test_pdbx.py

Fix improper quote escaping

---

src/biotite/structure/io/pdbx/convert.py
tests/structure/test_pdbx.py

Fix duplicate bonds in `chem_comp_bond`

---

doc/tutorial/structure/bonds.rst
doc/tutorial/structure/io.rst
src/biotite/structure/bonds.pyx
src/biotite/structure/io/mol/sdf.py
src/biotite/structure/io/pdbx/convert.py
tests/database/test_rcsb.py
tests/structure/test_bonds.py
tests/structure/test_pdbx.py

Support metal coordination as bond type

---

.github/workflows/test_and_deploy.yml
environment.yml
pyproject.toml
src/biotite/application/dssp/app.py
src/biotite/application/localapp.py
src/biotite/application/muscle/app3.py
src/biotite/application/muscle/app5.py
src/biotite/database/rcsb/query.py
src/biotite/sequence/io/genbank/file.py
tests/database/test_rcsb.py
tests/structure/test_basepairs.py

Furthermore the upcoming DSSP package from `conda-forge` is used

Support Python 3.13

---

CONTRIB.rst

Add myself to `CONTRIB.rst` (following #665).

Add @althonos to `CONTRIB.rst`

---

doc/examples/scripts/sequence/annotation/plasmid_map.py
doc/examples/scripts/sequence/homology/genome_comparison.py
environment.yml

Due to changes in external databases and software, some example outputs have changes. This PR brings the example scripts up to data accordingly

Refactor some examples

---

doc/tutorial/sequence/profiles.rst
src/biotite/sequence/profile.py
tests/test_doctest.py

Furthermore slicing of `SequenceProfile` objects is added

Expand tutorial about position specific scoring matrices

---

doc/preamble.py

Fix problems in current Biotite release

---

doc/apidoc.json
doc/conf.py
src/biotite/sequence/graphics/logo.py
src/biotite/visualize.py

Use `TextPath` for more precise scaled letters

---

src/biotite/structure/io/pdbx/convert.py
tests/structure/test_bonds.py

Corrects the bug addressed in #777 . This implementation is currently incomplete (a few pre-existing tests are failing).

Fix: altloc bonds interaction

---

tests/database/test_rcsb.py

Periodically the tests in `tests/database/test_rcsb.py` need to be adapted to new PDB entries, when a tested search result includes such new entry. To avoid this repetitive task, this PR adds also a cutoff date to the search queries in the tests. This means that new entries will not appear in the search results and the tests should work reliably over time.

Keep RCSB search results constant over time

---

.github/workflows/test_and_deploy.yml

Cache tutorial notebooks
